package kr.yuns.seoul;

import jakarta.servlet.http.HttpServletRequest;
import kr.yuns.JwtTokenProvider;
import kr.yuns.auth.data.dao.UserDao;
import kr.yuns.auth.data.enums.SeoulCountry;
import kr.yuns.seoul.data.dto.response.AttractionsResponseDto;
import kr.yuns.seoul.data.dto.response.BicycleResponseDto;
import kr.yuns.seoul.data.dto.response.ParkResponseDto;
import kr.yuns.seoul.data.enums.RiverPark;
import kr.yuns.seoul.service.SeoulService;
import lombok.AllArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.util.List;

@RestController
@RequestMapping("/api/v1/seoul")
@AllArgsConstructor
public class SeoulController {
    private final SeoulService seoulService;
    private final JwtTokenProvider tokenProvider;
    private final UserDao userDao;

    public Long GET_USER_ID_BY_TOKEN(HttpServletRequest request) {
        return userDao.getUserId(tokenProvider.getUserEmail(request));
    }

    @GetMapping("/shop")
    public ResponseEntity<?> getSeoulShoppingList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulShopList(seoulCountry);
    }

    @GetMapping("/karaoke")
    public ResponseEntity<?> getSeoulKaraokeList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulKaraokeList(seoulCountry);
    }

    @GetMapping("/food")
    public ResponseEntity<?> getSeoulFoodList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulFoodList(seoulCountry);
    }

    @GetMapping("/attractions")
    public ResponseEntity<List<AttractionsResponseDto>> getSeoulAttractionsList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getAttractionsList(seoulCountry);
    }

    @GetMapping("/bicycle")
    public ResponseEntity<List<BicycleResponseDto>> getSeoulBicycleList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulBicycleList(seoulCountry);
    }

    @GetMapping("/weather")
    public ResponseEntity<?> getSeoulWeather(HttpServletRequest request) throws IOException {
        return seoulService.getSeoulWeather(GET_USER_ID_BY_TOKEN(request));
    }

    @GetMapping("/park")
    public ResponseEntity<ParkResponseDto> getSeoulRiverParkList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulRiverParkList(seoulCountry);
    }

    @GetMapping("/park/detail")
    public ResponseEntity<?> getSeoulParkInfo(@RequestParam RiverPark riverPark) {
        return seoulService.getRiverInfo(riverPark);
    }

    // @PostMapping("/")
    // public ResponseEntity<GeneratedTrackResponseDto> getAutoGeneratedTrack(HttpServletRequest request,
    //         @RequestBody GeneratedTrackRequestDto generatedTrackRequestDto) throws JsonProcessingException {
    //     return seoulService.getAutoGeneratedTrack(GET_USER_ID_BY_TOKEN(request), generatedTrackRequestDto);
    // }
}