package kr.yuns.seoul.service.Impl;

import org.springframework.stereotype.Service;

import kr.yuns.saved.data.dao.SavedDao;
import kr.yuns.saved.service.SavedService;
import kr.yuns.seoul.service.AssistantService;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class AssistantServiceImpl implements AssistantService {
    private final SavedDao savedDao;
    private final SavedService savedService;

    private String TRACK_AUTO_OPTIONS_HOTEL = "소개글 마지막에, 이 내용을 추가할거야. 강남구에 방문하시는 분들을 위해 호" +
            "텔을 추천해 드릴게요. AA호텔, BB호텔, CC호텔의 호텔이 있으니 관광에 참고하시면 좋을 것 같아요!";

    private String TRACK_AUTO_OPTIONS_LOCATION = "소개글 마지막에, 이 내용을 추가할거야. 혹시 관광 다른 관광 장" +
            "소를 원한다면 채팅을 통해 함께 협의 후 장소를 변경하거나 추가할 수 있으니 채팅을 부탁드려요!";

    private String TRACK_AUTO_OPTIONS_START_LOCATION = "소개글 마지막에, 이 내용을 추가할거야. 혹시 관광을 시작할 때 만남을 원하" +
            "시는 장소가 있으면 그 곳으로 이동해 드릴 수 있어요! 채팅으로 말씀해 주세요!";

    private String TRACK_AUTO_SYSTEM_CONTENTS = "이 서비스는 한국에 방문하는 외국인과 실제 한국인이 만나서 한국에 대해 깊이 소개해" +
            "줄 수 있는 매칭 서비스야. 너는 사용자가 요청한 3가지에 대해 함께 할 여정에 대한 본문을 작성할거야." +
            "타이틀을 달 필요도 없고 그냥 본문만 작성해주면 돼." +
            "그리고 굳이 영어로 작성해 주지 않아도 돼. 반말로 작성하지마. 최대한 글을 길게 써줘. 인사말부터 본문, 마무리 인사까지. 최소 2,000자" +
            "이상으로 작성되어야 해.";

    private String TRACK_AUTO_SYSTEM_TITLE = "이 서비스는 한국에 방문하는 외국인과 실제 한국인이 만나서 한국에 대해 깊이 " +
            "소개해 줄 수 있는 매칭 서비스야. 이 글에 대해서 짧고 굵은 제목을 작성해줄래? 제목은 30자 이내로 작성해줘. " +
            "타이틀을 달 필요도 없고 그냥 본문만 작성해주면 돼.";

    private String TRACK_AUTO_SYSTEM_PREVIEW = "이 서비스는 한국에 방문하는 외국인과 실제 한국인이 만나서 한국에 대해 깊이 " +
            "소개해 줄 수 있는 매칭 서비스야. 이 글에 대해서 간단한 소개글을 작성해 줄래? 소개글은 50자 이내로 작성해줘. " +
            "타이틀을 달 필요도 없고 그냥 본문만 작성해주면 돼.";

    

    public String GET_TRACK_AUTO_CONTENT(String category, String value, String address, boolean required) {
        String GENERATED_CONTENTS = "이 카테고리의 분류는 " + category + "이야." + "여기서 " + value + "라는 장소에 방문할거야." + "주소는 " + address + "이야.";
        if(!required) {
            return GENERATED_CONTENTS;
        } else {
            return GENERATED_CONTENTS + "이 곳은 반드시 관광객과 방문할거야.";
        }
    }

    // @Override
    // public ResponseEntity<GeneratedTrackResponseDto> getAutoGeneratedTrack(
    //         Long userId, GeneratedTrackRequestDto generatedTrackRequestDto) throws JsonProcessingException {
    //     try {
    //         StringBuilder USER_CONTENTS = new StringBuilder();
    //         for (int i = 0; i < generatedTrackRequestDto.getSavedId().size(); i++) {
    //             Saved saved = savedDao.getSavedEntity(generatedTrackRequestDto.getSavedId().get(i));
    //             USER_CONTENTS.append(GET_TRACK_AUTO_CONTENT(saved.getCategory(), saved.getValue(), saved.getAddress(),
    //                     saved.getId().equals(generatedTrackRequestDto.getRequiredSavedId())));
    //         }

    //         if(generatedTrackRequestDto.isUseChangeLocationOptions()) {
    //             USER_CONTENTS.append(TRACK_AUTO_OPTIONS_HOTEL);
    //         }

    //         if(generatedTrackRequestDto.isUseCanStartVisitorsLocationOptions()) {
    //             USER_CONTENTS.append(TRACK_AUTO_OPTIONS_START_LOCATION);
    //         }

    //         if(generatedTrackRequestDto.isUseHotelOptions()) {
    //             USER_CONTENTS.append(TRACK_AUTO_OPTIONS_LOCATION);
    //         }

    //         JsonNode GPT_CONTENTS_JSON_NODE = assistantService.callChatGpt(TRACK_AUTO_SYSTEM_CONTENTS, USER_CONTENTS.toString());
    //         String GENERATED_TRACK_CONTENTS = GPT_CONTENTS_JSON_NODE.path("choices").get(0).path("message").path("content").asText();

    //         JsonNode GPT_TITLE_JSON_NODE = assistantService.callChatGpt(
    //                 TRACK_AUTO_SYSTEM_TITLE, GENERATED_TRACK_CONTENTS);

    //         JsonNode GPT_PREVIEW_JSON_NODE = assistantService.callChatGpt(
    //                 TRACK_AUTO_SYSTEM_PREVIEW, GENERATED_TRACK_CONTENTS);

    //         String GENERATED_TRACK_TITLE = GPT_TITLE_JSON_NODE.path("choices").get(0).path("message").path("content").asText();
    //         String GENERATED_TRACK_PREVIEW = GPT_PREVIEW_JSON_NODE.path("choices").get(0).path("message").path("content").asText();

    //         // GPT 호출 로그 저장
    //         assistantService.saveAssistantLog(USER_CONTENTS.toString(), GPT_CONTENTS_JSON_NODE, userId);
    //         assistantService.saveAssistantLog(GENERATED_TRACK_CONTENTS, GPT_TITLE_JSON_NODE, userId);
    //         assistantService.saveAssistantLog(GENERATED_TRACK_CONTENTS, GPT_PREVIEW_JSON_NODE, userId);

    //         // 사용자 장바구니 초기화
    //         savedService.resetSavedItem(userId);

    //         return ResponseEntity.status(HttpStatus.OK).body(GeneratedTrackResponseDto.builder()
    //                 .title(GENERATED_TRACK_TITLE)
    //                 .preview(GENERATED_TRACK_PREVIEW)
    //                 .content(GENERATED_TRACK_CONTENTS)
    //                 .build());
    //     } catch (Exception e) {
    //         return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
    //     }
    // }
}
