package com.koreanguide.koreanguidebackend.domain.seoul.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.koreanguide.koreanguidebackend.domain.auth.data.enums.SeoulCountry;
import com.koreanguide.koreanguidebackend.domain.seoul.data.dto.*;
import org.springframework.http.ResponseEntity;

import java.io.IOException;
import java.util.List;

public interface SeoulService {
    ResponseEntity<?> getSeoulWeather(Long userId) throws IOException;
    ResponseEntity<GeneratedTrackResponseDto> getAutoGeneratedTrack(Long userId,
                                                                    GeneratedTrackRequestDto generatedTrackRequestDto)
            throws JsonProcessingException;

    ResponseEntity<?> getSeoulKaraokeList(SeoulCountry seoulCountry);

    ResponseEntity<?> getSeoulShopList(SeoulCountry seoulCountry);
    ResponseEntity<?> getSeoulFoodList(SeoulCountry seoulCountry);

    ResponseEntity<List<BicycleResponseDto>> getSeoulBicycleList(SeoulCountry seoulCountry);

    ResponseEntity<List<AttractionsResponseDto>> getAttractionsList(SeoulCountry seoulCountry);

    ResponseEntity<ParkResponseDto> getSeoulRiverParkList(SeoulCountry seoulCountry);
}
