package com.koreanguide.koreanguidebackend.domain.seoul.controller;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.koreanguide.koreanguidebackend.config.security.JwtTokenProvider;
import com.koreanguide.koreanguidebackend.domain.auth.data.enums.SeoulCountry;
import com.koreanguide.koreanguidebackend.domain.seoul.data.dto.*;
import com.koreanguide.koreanguidebackend.domain.seoul.service.SeoulService;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiImplicitParam;
import io.swagger.annotations.ApiImplicitParams;
import io.swagger.annotations.ApiOperation;
import lombok.AllArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.util.List;

@Api(tags = {"Seoul API"})
@RestController
@RequestMapping("/api/v1/seoul")
@AllArgsConstructor
public class SeoulController {
    private final SeoulService seoulService;
    private final JwtTokenProvider jwtTokenProvider;

    public Long GET_USER_ID_BY_TOKEN(HttpServletRequest request) {
        return jwtTokenProvider.getUserIdByToken(request.getHeader("X-AUTH-TOKEN"));
    }

    @GetMapping("/shop")
    @ApiOperation(value = "쇼핑몰 리스트 조회")
    public ResponseEntity<?> getSeoulShoppingList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulShopList(seoulCountry);
    }

    @GetMapping("/karaoke")
    @ApiOperation(value = "노래방 리스트 조회")
    public ResponseEntity<?> getSeoulKaraokeList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulKaraokeList(seoulCountry);
    }

    @GetMapping("/food")
    @ApiOperation(value = "관광음식 리스트 조회")
    public ResponseEntity<?> getSeoulFoodList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulFoodList(seoulCountry);
    }

    @GetMapping("/attractions")
    @ApiOperation(value = "관광거리 리스트 조회")
    public ResponseEntity<List<AttractionsResponseDto>> getSeoulAttractionsList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getAttractionsList(seoulCountry);
    }

    @GetMapping("/bicycle")
    @ApiOperation(value = "따릉이 리스트 조회")
    public ResponseEntity<List<BicycleResponseDto>> getSeoulBicycleList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulBicycleList(seoulCountry);
    }

    @GetMapping("/weather")
    @ApiOperation(value = "날씨 정보 조회")
    @ApiImplicitParams({
            @ApiImplicitParam(name = "X-AUTH-TOKEN", value = "X-AUTH-TOKEN", required = true,
                    dataType = "String", paramType = "header")
    })
    public ResponseEntity<?> getSeoulWeather(HttpServletRequest request) throws IOException {
        return seoulService.getSeoulWeather(GET_USER_ID_BY_TOKEN(request));
    }

    @GetMapping("/park")
    @ApiOperation(value = "한강공원 리스트 조회")
    public ResponseEntity<ParkResponseDto> getSeoulRiverParkList(@RequestParam SeoulCountry seoulCountry) {
        return seoulService.getSeoulRiverParkList(seoulCountry);
    }

    @PostMapping("/")
    @ApiOperation(value = "자동 트랙 생성")
    @ApiImplicitParams({
            @ApiImplicitParam(name = "X-AUTH-TOKEN", value = "X-AUTH-TOKEN", required = true,
                    dataType = "String", paramType = "header")
    })
    public ResponseEntity<GeneratedTrackResponseDto> getAutoGeneratedTrack(HttpServletRequest request,
            @RequestBody GeneratedTrackRequestDto generatedTrackRequestDto) throws JsonProcessingException {
        return seoulService.getAutoGeneratedTrack(GET_USER_ID_BY_TOKEN(request), generatedTrackRequestDto);
    }
}
