package kr.yuns.seoul.service;

import kr.yuns.auth.data.enums.SeoulCountry;
import kr.yuns.seoul.data.dto.response.AttractionsResponseDto;
import kr.yuns.seoul.data.dto.response.BicycleResponseDto;
import kr.yuns.seoul.data.dto.response.ParkResponseDto;
import kr.yuns.seoul.data.enums.RiverPark;

import org.springframework.http.ResponseEntity;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;

public interface SeoulService {
    ResponseEntity<?> getSeoulWeather(Long userId) throws IOException, URISyntaxException;
    // ResponseEntity<GeneratedTrackResponseDto> getAutoGeneratedTrack(Long userId, GeneratedTrackRequestDto generatedTrackRequestDto) throws JsonProcessingException;
    ResponseEntity<?> getRiverInfo(RiverPark riverPark);
    ResponseEntity<?> getSeoulKaraokeList(SeoulCountry seoulCountry);
    ResponseEntity<?> getSeoulShopList(SeoulCountry seoulCountry);
    ResponseEntity<?> getSeoulFoodList(SeoulCountry seoulCountry);
    ResponseEntity<List<BicycleResponseDto>> getSeoulBicycleList(SeoulCountry seoulCountry);
    ResponseEntity<List<AttractionsResponseDto>> getAttractionsList(SeoulCountry seoulCountry);
    ResponseEntity<ParkResponseDto> getSeoulRiverParkList(SeoulCountry seoulCountry);
}